### DISCUSSION TITLE
[SOLVED] Where is the scrollbar on Selects with a considered number of items?

### DISCUSSION THREAD

**Discussion by jvsdurso** [heroui-inc/heroui#2310] [Q&A] [answered]
![image](https://github.com/nextui-org/nextui/assets/69814362/d60d3d49-ebc5-4bac-bd8f-e93248052868)

I'm pretty sure this Select has approximately 30 items or more, so I understand the Select should not open all of them. But where is the scrollbar to scroll it down? Is there any props or styling to make it visible?

**Comment by jvsdurso** [comment, marked as answer]
Hey guys, I've found an answer...

Seems that we can modify the components using "classNames" property, which you can choose the slot you want to style/override the style. 

Read on: https://nextui.org/docs/customization/override-styles

So, I've modified the "listbox" slot of the Select component using CSS:

```css
.listbox {
  width: 100%;
  max-height: 16rem;
  overflow-y: auto;
  scrollbar-width: thin;
  scroll-padding-top: 1.5rem;
  scroll-padding-bottom: 1.5rem;
}
```
