### ISSUE TITLE
[BUG] - Can select text with cursor like a normal person in Table

### ISSUE THREAD

**Issue by simPod** [heroui-inc/heroui#5413]
### HeroUI Version

2.7.0

### Describe the bug

There's some `:before` element inside of table cells that is intended to somehow help with text selection I guess. However, it's super unintuitive. In the video I'm trying to select "lead" when selecting from the back of the text. The table does not allow me to do so.

### Steps to Reproduce the Bug or Issue

1. render table
2. try to select part of the text from the back

### Expected behavior

Text is selected

### Screenshots or Videos

https://github.com/user-attachments/assets/b1653a4d-847f-4bbc-b878-87cdb30be979

### Operating System Version

macos

### Browser

Chrome

**Comment by simPod** [comment]
Also, same applies for headers.

I had to add

```css
table[role="grid"] td[role="gridcell"]::before {
    content: none;
}

table[role="grid"] th[role="columnheader"] {
    user-select: text !important;
}
```

to hotfix the behaviour.
